### ISSUE TITLE
Replace the current PluginFetchResourceListFromDrupal plugin with one that uses a Drupal View

### ISSUE THREAD

**Issue by mjordan** [mjordan/riprap#61]
The current PluginFetchResourceListFromDrupal plugin uses JSON:API to get a list of nodes, and then pick out the media for checking in Riprap. Replacing this plugin with one that gets a list of media via a Drupal View would be a lot more flexible and result in a much simpler plugin. This View (which [we will bundle with](https://github.com/mjordan/islandora_riprap/issues/27) Islandora Riprap) works fine for this purpose:

```
langcode: en
status: true
dependencies:
  config:
    - node.type.islandora_object
    - taxonomy.vocabulary.islandora_media_use
    - user.role.administrator
  content:
    - 'taxonomy_term:islandora_media_use:01891e5c-f649-48a9-a6aa-a228c856013f'
  module:
    - file
    - media
    - node
    - rest
    - serialization
    - taxonomy
    - user
_core:
  default_config_hash: _N_z8lq6meNQe29NBRcwZ0PHxszv9o8Lp58Do6q4iLc
id: riprap_resource_list
label: 'Riprap resource list'
module: views
description: 'Riprap resource (media) list'
tag: ''
base_table: media_field_data
base_field: mid
display:
  default:
    display_plugin: default
    id: default
    display_title: Master
    position: 0
    display_options:
      access:
        type: role
        options:
          role:
            administrator: administrator
      cache:
        type: tag
        options: {  }
      query:
        type: views_query
        options:
          disable_sql_rewrite: false
          distinct: false
          replica: false
          query_comment: ''
          query_tags: {  }
      exposed_form:
        type: basic
        options:
          submit_button: Apply
          reset_button: false
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          expose_sort_order: true
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        type: mini
        options:
          items_per_page: 50
          offset: 0
          id: 0
          total_pages: null
          expose:
            items_per_page: false
            items_per_page_label: 'Items per page'
            items_per_page_options: '5, 10, 25, 50'
            items_per_page_options_all: false
            items_per_page_options_all_label: '- All -'
            offset: false
            offset_label: Offset
          tags:
            previous: ‹‹
            next: ››
      style:
        type: serializer
      row:
        type: fields
        options:
          inline: {  }
          separator: ''
          hide_empty: false
          default_field_elements: true
      fields:
        changed:
          id: changed
          table: media_field_data
          field: changed
          relationship: none
          group_type: group
          admin_label: ''
          label: ''
          exclude: false
          alter:
            alter_text: false
            text: ''
            make_link: false
            path: ''
            absolute: false
            external: false
            replace_spaces: false
            path_case: none
            trim_whitespace: false
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: false
            max_length: 0
            word_boundary: true
            ellipsis: true
            more_link: false
            more_link_text: ''
            more_link_path: ''
            strip_tags: false
            trim: false
            preserve_tags: ''
            html: false
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: false
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: true
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          click_sort_column: value
          type: timestamp
          settings:
            date_format: custom
            custom_date_format: 'Y-m-d\TH:i:sO'
            timezone: ''
          group_column: value
          group_columns: {  }
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
          entity_type: media
          entity_field: changed
          plugin_id: field
        mid:
          id: mid
          table: media_field_data
          field: mid
          relationship: none
          group_type: group
          admin_label: ''
          label: ''
          exclude: false
          alter:
            alter_text: false
            text: ''
            make_link: false
            path: ''
            absolute: false
            external: false
            replace_spaces: false
            path_case: none
            trim_whitespace: false
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: false
            max_length: 0
            word_boundary: true
            ellipsis: true
            more_link: false
            more_link_text: ''
            more_link_path: ''
            strip_tags: false
            trim: false
            preserve_tags: ''
            html: false
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: false
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: true
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          click_sort_column: value
          type: number_integer
          settings:
            thousand_separator: ''
            prefix_suffix: false
          group_column: value
          group_columns: {  }
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
          entity_type: media
          entity_field: mid
          plugin_id: field
      filters:
        status:
          value: '1'
          table: media_field_data
          field: status
          plugin_id: boolean
          entity_type: media
          entity_field: status
          id: status
          expose:
            operator: ''
            operator_limit_selection: false
            operator_list: {  }
          group: 1
        field_media_use_target_id:
          id: field_media_use_target_id
          table: media__field_media_use
          field: field_media_use_target_id
          relationship: none
          group_type: group
          admin_label: ''
          operator: or
          value:
            17: 17
          group: 1
          exposed: false
          expose:
            operator_id: ''
            label: ''
            description: ''
            use_operator: false
            operator: ''
            operator_limit_selection: false
            operator_list: {  }
            identifier: ''
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
            reduce: false
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
          reduce_duplicates: false
          type: select
          limit: true
          vid: islandora_media_use
          hierarchy: false
          error_message: true
          plugin_id: taxonomy_index_tid
        type:
          id: type
          table: node_field_data
          field: type
          relationship: field_media_of
          group_type: group
          admin_label: ''
          operator: in
          value:
            islandora_object: islandora_object
          group: 1
          exposed: false
          expose:
            operator_id: ''
            label: ''
            description: ''
            use_operator: false
            operator: ''
            operator_limit_selection: false
            operator_list: {  }
            identifier: ''
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
            reduce: false
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
          entity_type: node
          entity_field: type
          plugin_id: bundle
      sorts:
        changed:
          id: changed
          table: media_field_data
          field: changed
          relationship: none
          group_type: group
          admin_label: ''
          order: ASC
          exposed: false
          expose:
            label: ''
          granularity: second
          entity_type: media
          entity_field: changed
          plugin_id: date
      header: {  }
      footer: {  }
      empty: {  }
      relationships:
        field_media_of:
          id: field_media_of
          table: media__field_media_of
          field: field_media_of
          relationship: none
          group_type: group
          admin_label: 'field_media_of: Content'
          required: true
          plugin_id: standard
        field_media_file_target_id:
          id: field_media_file_target_id
          table: media__field_media_file
          field: field_media_file_target_id
          relationship: none
          group_type: group
          admin_label: 'file from field_media_file'
          required: false
          plugin_id: standard
        field_media_image_target_id:
          id: field_media_image_target_id
          table: media__field_media_image
          field: field_media_image_target_id
          relationship: none
          group_type: group
          admin_label: 'image from field_media_image'
          required: false
          plugin_id: standard
      arguments: {  }
      display_extenders: {  }
      title: 'Riprap resource list'
    cache_metadata:
      max-age: -1
      contexts:
        - 'languages:language_content'
        - 'languages:language_interface'
        - request_format
        - url.query_args
        - user
        - user.roles
      tags: {  }
  rest_export_1:
    display_plugin: rest_export
    id: rest_export_1
    display_title: 'REST export'
    position: 1
    display_options:
      display_extenders: {  }
      path: riprap_resource_list
      pager:
        type: full
        options:
          items_per_page: 100
          offset: 0
          id: 0
          total_pages: null
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page: false
            items_per_page_label: 'Items per page'
            items_per_page_options: '5, 10, 25, 50'
            items_per_page_options_all: false
            items_per_page_options_all_label: '- All -'
            offset: false
            offset_label: Offset
          quantity: 9
      style:
        type: serializer
        options:
          formats:
            json: json
      row:
        type: data_field
        options:
          field_options:
            uuid:
              alias: ''
              raw_output: true
      display_description: 'Riprap resouce (media) list'
      auth:
        - basic_auth
    cache_metadata:
      max-age: -1
      contexts:
        - 'languages:language_content'
        - 'languages:language_interface'
        - request_format
        - url.query_args
        - user
        - user.roles
      tags: {  }
```

Filters for media use tags, parent node content types, tags, etc. are done in the Views GUI as with any other View:
